# -*- coding: utf-8 -*-
# setuptools references https://docs.python.org/3/distutils/setupscript.html
# pip references https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56


# first export requirements.txt file by using
# pip list --format=freeze > requirements.txt

# then upload to pypi using
# python setup.py sdist
# twine upload dist/*

from setuptools import setup

'''
import os
# read the requirements file
thelibFolder = os.path.dirname(os.path.realpath(__file__))
requirementPath = thelibFolder + '/requirements.txt'
install_requires = []  # Here we'll get: ["gunicorn", "docutils>=0.3", "lxml==0.5a7"]
if os.path.isfile(requirementPath):
    with open(requirementPath) as f:
        install_requires = f.read().splitlines()
'''
setup(
    name='analogistics',
    version='0.1.3',
    description='Analytical Tools for Logistics System Design and Operations Management',
    url='https://github.com/aletuf93/analogistics',
    author='Alessandro Tufano',
    author_email='aletuf@gmail.com',
    license='MIT',
    packages=['analogistics'],
    install_requires=[   'affine==2.3.0',
                         'anyio==2.2.0',
                         'async-generator==1.10',
                         'attrs==21.2.0',
                         'Babel==2.9.1',
                         'backports.functools-lru-cache==1.6.4',
                         'bleach==4.1.0',
                         'branca==0.4.2',
                         'certifi==2020.6.20',
                         'click==7.1.2',
                         'click-plugins==1.1.1',
                         'cligj==0.7.2',
                         'colorama==0.4.4',
                         'contextvars==2.4',
                         'cycler==0.11.0',
                         'dataclasses==0.8',
                         'decorator==4.4.2',
                         'defusedxml==0.7.1',
                         'entrypoints==0.3',
                         'et-xmlfile==1.0.1',
                         'Fiona==1.8.13.post1',
                         'folium==0.0.0',
                         'future==0.18.2',
                         'GDAL==3.0.2',
                         'geocoder==1.38.1',
                         'geopandas==0.9.0',
                         'idna==3.1',
                         'immutables==0.16',
                         'importlib-metadata==3.10.1',
                         'ipykernel==5.3.4',
                         'ipython==5.8.0',
                         'ipython-genutils==0.2.0',
                         'jdcal==1.4.1',
                         'Jinja2==3.0.3',
                         'joblib==1.1.0',
                         'json5==0.9.5',
                         'jsonschema==3.2.0',
                         'jupyter-client==7.0.6',
                         'jupyter-core==4.7.1',
                         'jupyter-server==1.4.1',
                         'jupyterlab==3.2.3',
                         'jupyterlab-server==2.8.2',
                         'kiwisolver==1.3.1',
                         'Mako==1.1.6',
                         'Markdown==3.3.4',
                         'MarkupSafe==2.0.1',
                         'matplotlib==3.2.2',
                         'mistune==0.8.4',
                         'munch==2.5.0',
                         'nbclassic==0.2.6',
                         'nbconvert==5.6.1',
                         'nbformat==5.1.3',
                         'nest-asyncio==1.5.1',
                         'networkx==2.5.1',
                         'notebook==5.7.11',
                         'numpy==1.19.5',
                         'openpyxl==3.0.5',
                         'osmnx==1.1.1',
                         'packaging==21.0',
                         'pandas==0.25.3',
                         'pandocfilters==1.5.0',
                         'patsy==0.5.2',
                         'pdoc3==0.8.1',
                         'pickleshare==0.7.5',
                         'pip==21.3.1',
                         'plotly==5.4.0',
                         'prometheus-client==0.12.0',
                         'prompt-toolkit==1.0.15',
                         'Pygments==2.10.0',
                         'pyparsing==3.0.6',
                         'pyproj==2.6.1.post1',
                         'pyrsistent==0.17.3',
                         'python-dateutil==2.8.2',
                         'pytz==2021.3',
                         'pywin32==227',
                         'pywinpty==0.5.7',
                         'pyzmq==22.3.0',
                         'rasterio==1.1.0',
                         'ratelim==0.1.6',
                         'requests==2.12.5',
                         'Rtree==0.9.7',
                         'scikit-learn==0.24.2',
                         'scipy==1.5.3',
                         'seaborn==0.11.0',
                         'Send2Trash==1.8.0',
                         'setuptools==49.6.0.post20210108',
                         'Shapely==1.7.1',
                         'simplegeneric==0.8.1',
                         'sip==4.19.24',
                         'six==1.16.0',
                         'sniffio==1.2.0',
                         'snuggs==1.4.7',
                         'statsmodels==0.12.1',
                         'tenacity==8.0.1',
                         'terminado==0.9.4',
                         'testpath==0.5.0',
                         'threadpoolctl==3.0.0',
                         'tornado==6.1',
                         'traitlets==4.3.3',
                         'typing-extensions==3.10.0.2',
                         'wcwidth==0.2.5',
                         'webencodings==0.5.1',
                         'wheel==0.37.0',
                         'wincertstore==0.2',
                         'zipp==3.6.0'],
    download_url='https://github.com/aletuf93/analogistics/archive/refs/tags/v0.1.tar.gz',
    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'Programming Language :: Python :: 3.7',
    ],
)
